import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { LayoutWrapper } from "@/components";
 task/responsive_design

import { Toaster } from "react-hot-toast";

 main
import { AuthProvider } from "@/context/AuthContext";
import { UIProvider } from "@/context/UIContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UIProvider>
 task/responsive_design
            <LayoutWrapper>{children}</LayoutWrapper>

            <Toaster
              position="top-right"
              toastOptions={{
                success: {
                  style: {
                    background: "#10b981",
                    color: "white",
                  },
                },
                error: {
                  style: {
                    background: "#ef4444",
                    color: "white",
                  },
                },
              }}
            />
            <nav className="flex gap-4 p-4 bg-gray-100">
              <Link href="/">Home</Link>
              <Link href="/login">Login</Link>
              <Link href="/dashboard">Dashboard</Link>
              <Link href="/users/1">User 1</Link>
            </nav>

            {children}
 main
          </UIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
